Repository playtron-os/gameos, pull requests merged in 2025-07, with the labels that each got.

#237 feature/OS-376-selinux
  README.md
  containerfiles/unstable
  rootfs/etc/yum.repos.d/nobara-41-i386.repo
  rootfs/etc/yum.repos.d/nobara-41-x86_64.repo
  rootfs/etc/yum.repos.d/playtron-gaming-x86_64.repo
Labels: enhancement

#236 Take a screenshot when collecting a system report
  rootfs/usr/bin/playtronos-systemreport
Labels: enhancement

#249 fix: remove sleep-rfkill service
  containerfiles/unstable
  rootfs/usr/lib/systemd/system-preset/50-playtron.preset
  rootfs/usr/lib/systemd/system/sleep-rfkill.service
Labels: bug

#250 remove custom os update location config file during factory reset
  rootfs/usr/bin/playtron-factory-reset
Labels: bug

#251 fix(ROG Ally X): add LEDs to device config
  rootfs/usr/share/inputplumber/devices/25-playtron-rog_ally_x.yaml
Labels: enhancement

#254 update package versions for 1.0.0.14
  containerfiles/stable
  containerfiles/unstable
Labels: enhancement

#255 fix: include all file updates
  containerfiles/stable
Labels: bug

#257 update package versions for 1.0.0.22 build
  containerfiles/stable
Labels: enhancement

#258 Add download link
  README.md
Labels: documentation
