Repository playtron-os/gameos, pull requests merged in 2025-08, with the labels that each got.

#263 fix(systemreport): use atom for taking screenshot and include Grid props in report
  rootfs/usr/bin/playtronos-systemreport
Labels: bug

#270 fix: install Linux kernel 6.15.8
  containerfiles/stable
Labels: bug

#271 docs/devices autotdp
  DEVICES.md
  rootfs/usr/lib/udev/hwdb.d/60-powerstation-autostart.hwdb
Labels: bug, documentation

#272 fix(containerfiles): fix NVIDIA driver build
  containerfiles/stable
Labels: bug

#277 Misc device updates
  DEVICES.md
Labels: documentation

#278 fix(stable): install our new kernel
  containerfiles/stable
Labels: bug

#280 feat(inputplumber): enable meta key
  containerfiles/stable
  containerfiles/unstable
  rootfs/usr/share/inputplumber/capability_maps/kbd-meta.yaml
  rootfs/usr/share/inputplumber/devices/60-keyboard-meta.yaml
Labels: enhancement

#282 docs(DEVICES): list brightness control as partially supported
  DEVICES.md
Labels: documentation

#285 Stable 1.1
  DEVICES.md
  containerfiles/stable
  containerfiles/unstable
  rootfs/usr/lib/systemd/user-preset/50-playtron.preset
  rootfs/usr/lib/udev/hwdb.d/60-powerstation-autostart.hwdb
  rootfs/usr/share/inputplumber/capability_maps/kbd-meta.yaml
  rootfs/usr/share/inputplumber/devices/60-keyboard-meta.yaml
  rootfs/usr/share/plymouth/themes/spinner/watermark.png
Labels: enhancement
