Repository playtron-os/gameos, pull requests merged in 2025-06, with the labels that each got.

#217 [containerfiles] Use 'bootc container lint'
  containerfiles/stable
  containerfiles/unstable
Labels: enhancement

#224 docs: add attributions
  attributions/dotnet-attributions.md
  attributions/grid-attributions.md
  attributions/playserve-attributions.md
Labels: documentation

#226 Add a package to silence Steam errors
  containerfiles/unstable
Labels: enhancement

#228 fix build: remove missing package
  containerfiles/unstable
Labels: bug

#229 update package versions for 0.21.2.1 build
  containerfiles/stable
Labels: enhancement
